#!/bin/bash
# Automatically copies HTTP OS to a floppy disk

if [ "$EUID" -ne 0 ]; then
    echo "This script must be run as root!"
    exit 1
fi

function write_floppy {
# Check serial and label
serial=$(sudo dd if=/dev/$selected_drive bs=1 skip=38 count=4 status=none | xxd -p)
if [ "$serial" != "29031721" ]; then
    while true; do
        read -p "Are you sure you want to write to \"/dev/$selected_drive\"? THIS WILL OVERWRITE DATA! (Y/n)" answer
        case "$answer" in
            [Yy]|[Yy][Ee][Ss]|"")
                break
                ;;
            [Nn]|[Nn][Oo])
                echo Exiting...
                exit 0
                ;;
            *)
                echo Unknown input.
                ;;
        esac
    done
    dd if=./httpos.img | pv -s 1440K | dd of=/dev/$selected_drive bs=4096
    echo Done!
    exit 0
fi

}

drives=$(lsblk --nodeps --noheadings --output NAME,SIZE | awk '$2 == "1.4M"')

# Check if there are drives available
if [ -z "$drives" ]; then
    echo "No 1.44 Floppy drives found..."
    echo Exiting...
    exit 1
fi

# Check if there is only one floppy drive
if [ $(echo "$drives" | wc -l) -eq 1 ]; then
    selected_drive=$(echo "$drives" | awk '{print $1}')
    write_floppy
    exit 0
fi

# Display a numbered menu
echo "Select a floppy drive:"
echo "$drives" | awk '{print NR")", $1, $2}'

# Prompt for selection
read -p "Select a drive (enter the number): " choice

# Validate the choice
if [[ "$choice" =~ ^[1-9]+$ && "$choice" -le $(echo "$drives" | wc -l) ]]; then
    selected_drive=$(echo "$drives" | awk -v c="$choice" 'NR==c {print $1}')
    write_floppy
    exit 0
else
    echo "Invalid selection. Please enter a valid number."
    echo Exiting...
    exit 1
fi